config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  # enable sidekiq gui background jobs
  mount Sidekiq::Web => '/sidekiq'

  root to: 'home#index'

  resources :imports, only: [ :index ] do
    collection do
      get 'import_product'
      get 'import_in_transit'
      get 'import_on_hand'
      post 'import'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/import_request.rb
class ImportRequest < ApplicationRecord
  default_scope { order(created_at: :desc) }
  
  mount_uploader :import_file, ImportFileUploader
  validates_presence_of :import_file

  IMPORT_FOR = { 
                 product: 'Product', 
                 in_transit: 'InTransitInventory', 
                 on_hand: 'OnHandInventory'
               }

  after_create :set_background_job

  private

  def set_background_job
		self.update(state: "inprocess")
		unless self.extract_time.present?
			ImportRequestJob.set(wait_until: Time.now ).perform_later(self.id)
  	else
  		ImportRequestJob.set(wait_until: self.extract_time ).perform_later(self.id)
  	end
  end
end

app/models/inventory.rb
class Inventory < ApplicationRecord

	TYPE = {on_hand: 'Onhand', in_transit: 'Transit'}
end

app/models/product.rb
class Product < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController
	
	def index
		@imports = ImportRequest.all
	end

	def import_product
		@request = ImportRequest.new
	end

	def import_in_transit
		@request = ImportRequest.new
	end

	def import_on_hand
		@request = ImportRequest.new
	end

	def import
		@request = ImportRequest.new(import_request_params)
		if @request.save
			redirect_to imports_path
		else
			render :action => params[:request_from]
		end
	end

	private

	def import_request_params
		params.require(:import_request).permit(:import_file, :import_for, :extract_time)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/imports_helper.rb
module ImportsHelper
end

app/views/imports/_import_inventory.html.erb
<div class="row">
  <main class="col-sm-12 col-md-12">
    <%= form_for @request, { url: import_imports_path , class: 'form-inline mt-2 mt-md-0' , multipart: true } do |f| %>

      <div class="form-group">
        <%= @request.errors.full_messages.first if @request.errors.any? %>
      </div>

      <%= f.hidden_field :import_for, value: import_for %>
      <%= hidden_field_tag :request_from, params[:action] %>
      <div class="form-group">
        <%= f.file_field :import_file %>
      </div>
      <div class="form-group">
        <%= f.datetime_field :extract_time, min: Time.now %>
      </div>
      <div class="form-group">
        <%= f.submit "Import Prodcts" , class: 'btn btn-primary'%>
      </div>
    <% end %>
  </main>
</div>

app/views/imports/import_in_transit.html.erb
<%= stylesheet_link_tag    'handsontable.full' %>
<%= javascript_include_tag 'csv_import' %>

<div class="container-fluid">
  <div class="row col-sm-12 col-md-12 mt-5">
    <h2 class="mr-auto">Import in transit Inventory</h2>
  </div>
  <%= render partial: 'import_inventory', locals: { import_for: ImportRequest::IMPORT_FOR[:in_transit]} %>
</div>

<br>
<div id="import_file_rows"></div>

app/views/imports/import_on_hand.html.erb
<%= stylesheet_link_tag    'handsontable.full' %>
<%= javascript_include_tag 'csv_import' %>

<div class="container-fluid">
  <div class="row col-sm-12 col-md-12 mt-5">
    <h2 class="mr-auto">Import On Hand Inventory</h2>
  </div>
  <%= render partial: 'import_inventory', locals: { import_for: ImportRequest::IMPORT_FOR[:on_hand]} %>
</div>

<br>
<div id="import_file_rows"></div>

app/views/imports/import_product.html.erb
<%= stylesheet_link_tag    'handsontable.full' %>
<%= javascript_include_tag 'csv_import' %>

<div class="container-fluid">
  <div class="row col-sm-12 col-md-12 mt-5">
    <h2 class="mr-auto">Import Product</h2>
  </div>
  <div class="row">
    <main class="col-sm-12 col-md-12">
      <%= form_for @request, { url: import_imports_path , class: 'form-inline mt-2 mt-md-0' , multipart: true } do |f| %>
        <div class="form-group">
          <%= @request.errors.full_messages.first if @request.errors.any? %>
        </div>
        <%= hidden_field_tag :request_from, params[:action] %>
        <%= f.hidden_field :import_for, value: ImportRequest::IMPORT_FOR[:product] %>
        <div class="form-group">
          <%= f.file_field :import_file %>
        </div>
        <div class="form-group">
          <%= f.submit "Import Prodcts", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </main>
  </div>
</div>


<br>
<div id="import_file_rows"></div>
<br>

app/views/imports/index.html.erb
<div class="container-fluid">
  <div class="row col-sm-12 col-md-12 mt-5">
    <h2 class="mr-auto">Import Requests</h2>
    <%= link_to 'Import Product', import_product_imports_path, class: "btn btn-primary ml-2 mb-2"%>
    <%= link_to 'Import InTransite Inventory', import_in_transit_imports_path, class: "btn btn-primary ml-2 mb-2"%>
    <%= link_to 'Import OnHand Inventory', import_on_hand_imports_path, class: "btn btn-primary ml-2 mb-2"%>
  </div>
  <div class="row">
    <main class="col-sm-12 col-md-12">
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Import Request For</th>
              <th>Current Status</th>
              <th>Desciption</th>
              <th>ExtractAt</th>
              <th>Requested At</th>
              <th>Error Message</th>
            </tr>
          </thead>
          <tbody>
            <% @imports.each do |imp|%>
              <tr>
                <td><%= imp.import_for %></td>
                <td><%= imp.state %></td>
                <td><%= imp.message %></td>
                <td><%= imp.extract_time ? imp.extract_time.strftime("%m/%d/%Y at %I:%M%p") : 'N/A' %></td>
                <td><%= imp.created_at.strftime("%m/%d/%Y at %I:%M%p") %></td>
                <td><%= imp.error_message %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </main>
  </div>
</div>

app/views/layouts/_top_bar.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <a class="navbar-brand mr-auto" href="#">Import App</a>
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to "Imports", imports_path, class: 'nav-link'%>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImportTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render :partial => 'layouts/top_bar'%>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%#= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->


    </div> <!-- /container -->

  </body>
</html>